### PR TITLE
French translations for HRD

### PR DESCRIPTION
**Pull request by aliceumons**
Adds support for French in the HRD task.

### CODE REVIEW

**Comment by LegrandNico** [comment]
Thank you for your contribution @aliceumons , this translation is highly valuable :raised_hands: 

I will fix the tests after merging. Did you try to run this new version of the task?

**Comment by aliceumons** [comment]
You're welcome! The mouse version runs correctly except for the progress message (with the percentage completed) which I was unable to translate. For the keyboard version, the confidence scale is still displayed in English. There are also overlays of the icons in case of feedback for the given answer.

**Comment by LegrandNico** [comment]
I am considering completely removing the keyboard version for future releases as it is a bit sub-optimal for confidence ratings and it is apparently prone to bugs. We have not really used this keyboard version ourselves so I cannot guarantee as much as the mouse version, so I think it would be better to use only this one. Do you know which one you will be using?

**Comment by aliceumons** [comment]
It doesn't matter much, so i think we will use the mouse version.

**Pull request merged**
